CRG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import *

app_name = "website"
urlpatterns = [
    path('', home, name="home"),
    path('article=<int:pk>', article_detail, name="article_detail"),
    path('category=<int:pk>/', list_articles, name="list_articles"),
    path('subcategory=<int:pk>/', list_sub_articles, name="list_sub_articles"),
    path('fields=<str:fields>/', list_searched_articles, name="list_searched_articles"),
    path('introductions', introductions, name="introductions"),
    path('our_team', our_team, name="our_team"),
    path('to_publish', to_publish, name="to_publish"),
]

website/models.py
from django.db import models
from datetime import date


class Author(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50)
    order = models.IntegerField(null=True)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['-order',
                    'name',
                    ]

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="subcategories")

    class Meta:
        verbose_name_plural = 'Subcategories'
        ordering = ['name']

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=140)
    content = models.TextField()
    preview = models.TextField(blank=True, null=True)
    endnotes = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="thumbnails/", blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.SET_NULL, null=True)
    featured = models.BooleanField(default=False)

    @property
    def textdump(self):
        return f'{self.title} {self.content} {self.date} {self.author} {self.subcategory}'

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.title


class Image(models.Model):
    image = models.ImageField(upload_to=f'{date.today().year}/{date.today().month}/{date.today().day}')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='images', null=True)

    def __str__(self):
        return f'https://crgreview.com/media/{self.image.name}'


class StatusUpdate(models.Model):
    content = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.content[0:10] + '...'


class SubmissionRequest(models.Model):
    content = models.TextField()

    def __str__(self):
        return "Submission request: " + str(self.id)

website/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import *

ARTICLES_PER_PAGE = 10


def home(request):
    latest = []
    for category in Category.objects.all():
        article = Article.objects.filter(subcategory__category=category).exclude(featured=False)[0:1]
        if article:
            latest.append(article[0])

    status_updates = StatusUpdate.objects.all()[0:10]
    submission_request = SubmissionRequest.objects.all()[0]
    return render(request, 'website/home.html', {
        'articles': latest,
        'status_updates': status_updates,
        'submission_request': submission_request,
    })


def list_articles(request, pk):
    category = Category.objects.get(pk=pk)
    article_list = Article.objects.filter(subcategory__category=category)
    feature_article = Article.objects.filter(subcategory__category=category).exclude(featured=False)
    if feature_article:
        feature_article = feature_article[0]
    else:
        feature_article = None

    paginator = Paginator(article_list, ARTICLES_PER_PAGE)

    page = request.GET.get('page')
    articles = paginator.get_page(page)
    return render(request, 'website/list_articles.html', {
        'articles': articles,
        'feature_article': feature_article,
        'category': category,
    })


def list_sub_articles(request, pk):
    subcategory = Subcategory.objects.get(pk=pk)
    category = subcategory.category

    article_list = Article.objects.filter(subcategory=subcategory)
    feature_article = Article.objects.filter(subcategory__category=category).exclude(featured=False)
    if feature_article:
        feature_article = feature_article[0]
    else:
        feature_article = None

    paginator = Paginator(article_list, ARTICLES_PER_PAGE)

    page = request.GET.get('page')
    articles = paginator.get_page(page)
    return render(request, 'website/list_articles.html', {
        'articles': articles,
        'category': category,
        'subcategory': subcategory,
        'feature_article': feature_article,
    })


def list_searched_articles(request, fields):
    article_list = (Article.objects.filter(title__contains=fields) |
                    Article.objects.filter(content__contains=fields) |
                    Article.objects.filter(author__name__contains=fields))

    paginator = Paginator(article_list, ARTICLES_PER_PAGE)

    page = request.GET.get('page')
    articles = paginator.get_page(page)
    return render(request, 'website/list_articles.html', {
        'articles': articles,
        'fields': fields,
    })


def article_detail(request, pk):
    article = Article.objects.get(pk=pk)
    return render(request, 'website/article_detail.html', {
        'article': article,
    })


def introductions(request):
    return render(request, 'website/introductions.html')


def our_team(request):
    return render(request, 'website/our_team.html')


def to_publish(request):
    return render(request, 'website/to_publish.html')

templates/layout.html
{% load static %}
{% load extras %}

{% with "1.0.1" as css_version %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Facebook Tags -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="Contemporary Review of Genocides">
    <meta property="fb:app_id" content="288911271809413">
    {% block og_image %}<meta property="og:image" content="https://crgreview.com/static/images/logo.png"/>{% endblock og_image %}
    {% block og_description %}<meta property="og:description" content="Contemporary Review of Genocides and Political Violence">{% endblock og_description %}
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/styles.css" %}?ver={{ css_version }}">
    <title>{% block title %}Contemporary Review of Genocides{% endblock title %}</title>
    {% block head %}{% endblock head %}

</head>
<body>
{% block header %}
    <header class="mb-3">
        <div id="site_header" class="d-md-flex align-items-center">
            <div id="logo" style="background-image:url({% static 'images/crg.png' %})"></div>
            <div id="indig">
                CRG occupies the unceded territory of the Haudenosaunee Confederacy, specifically the Kanien’kehá:ka
                people.  It is part of a wider genocide which continues today.  We acknowledge the injustice of such
                a publication originating in this context and hope its contribution can mitigate this unfairness.
            </div>
        </div>
        {% menu_bar %}
    </header>
{% endblock header %}
{% block main %}{% endblock main %}
{% block footer %}
    <footer>
        <a href="https://www.facebook.com/CRGjournal" target="_blank"><img src="{% static "images/facebook.png" %}"></a>
        <a><img src="{% static "images/instagram.png" %}"></a>
        <a><img src="{% static "images/twitter.png" %}"></a>
    </footer>
{% endblock footer %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="{% static "js/scripts.js" %}?ver={{ css_version }}"></script>
{% block scripts %}{% endblock scripts %}
</body>
</html>

{% endwith %}

website/templates/website/about.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}?ver={{ css_version }}">
{% endblock head %}

{% block main %}
    <main>
        <div class="container">
            <div class="subcategories d-flex flex-wrap justify-content-center">
                <a class="btn btn-outline-secondary" href="{% url "website:introductions" %}">Introductions</a>
                <a class="btn btn-outline-secondary" href="{% url "website:to_publish" %}">To Publish</a>
                <a class="btn btn-outline-secondary" href="{% url "website:our_team" %}">Our Team</a>
            </div>
            {% block blurb %}{% endblock blurb %}
        </div>
    </main>
{% endblock main %}

website/templates/website/article_detail.html
{% extends "layout.html" %}
{% load static %}
{% load extras %}

{% block og_image %}
    {% if article.image %}
    <meta property="og:image" content="https://crgreview.com{{ article.image.url }}">
    {% endif %}
{% endblock og_image %}

{% block og_description %}
    {% if article.preview %}
    <meta property="og:description" content="{{ article.preview }}">
    {% endif %}
{% endblock og_description %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/article_detail.css" %}?ver={{ css_version }}">
{% endblock head %}

{% block title %}{{ article.title }}{% endblock title %}

{% block main %}
    <main>
        <div class="container">
            <a onclick="window.history.back()" id="back">&lsaquo;&lsaquo; back</a>
            <h2 id="title">{{ article.title }}</h2>
            {% if article.image %}
                <div id="banner" style="background-image:url({{ article.image.url }})"></div>
            {% endif %}
            <div id="article_info">
                <p><small>
                    By {{ article.author.name }}<br>
                    Published {{ article.date|date:'Y-m-d' }}<br>
                </small></p>
            </div>
            <div id="content">
                {{ article.content|markdown_to_html|linebreaks }}
            </div>
            {% if article.endnotes %}<div id="endnotes">{{ article.endnotes|linebreaks }}</div>{% endif %}
        </div>
    </main>
{% endblock main %}

website/templates/website/home.html
{% extends "layout.html" %}
{% load static %}
{% load extras %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/home.css" %}?ver={{ css_version }}">

{% endblock head %}

{% block main %}
    <main>
        <div id="wrapper" class="container-fluid d-xl-flex flex-xl-row">
            <div id="article-grid" class="container-fluid mb-4">
                {% for article in articles %}
                    <a href="{% url "website:article_detail" article.pk %}"
                       class='grid-item'
                       {% if article.image %}
                       style="background-image: url('{{ article.image.url }}');"
                       {% endif %}>
                        <div class="item-heading">
                            <p class='item-subcategory'>{{ article.subcategory.category }}</p>
                        </div>
                        <p class='item-title'>{{ article.title }}</p>
                        {% if article.preview %}<p class='item-preview'><em>{{ article.preview|truncatechars:100 }}</em></p>{% endif %}
                        <div class="item-footer">
                            <p class='item-author'>{{ article.author.name }}<p>
                            <p class='item-date'>{{ article.date|date:'Y-m-d' }}</p>
                        </div>
                    </a>
                {% endfor %}
                <div id="call_to_action" class='grid-item'>
                    <div>
                        {{ submission_request.content|markdown_to_html|linebreaks }}
                    </div>
                </div>
            </div>
            <div id="sidebar" class="container-fluid">
                <h3><em>Weekly Briefing:</em></h3>
                <div id="info-cards">
                    {% for update in status_updates %}
                        <div class="info-card">
                            <div class="info-card-body">
                                <p>{{ update.content|markdown_to_html|linebreaks }}</p>
                                <p><em> - {{ update.date }}</em></p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock main %}

website/templates/website/introductions.html
{% extends 'website/about.html' %}

{% block title %}Introductions{% endblock title %}

{% block blurb %}
    <h1>Introductions: Why are we here?</h1>
    <p>
        Genocide is a recent term. In 1944, when news on what would become known as ‘the holocaust’ was reaching general
        audiences, it was, like today, inconceivable. In response, Jewish scholar Raphael Lemkin created the term –his
        notebooks are filled with failed attempts– from the Greek “genoc” to mean tribe and Latin “cide” to mean murder.
        But no Nazis at the time were tried for genocide, and Hitler never even heard the term. Its meaning is deeper,
        its allegations older, and its permutations newer. Its questions today remain unanswered.
    </p>
    <p>
        Canada is no stranger to genocide, although Canadians sometimes can be. We are a nation founded on genocide, in
        an era when genocide has fallen out of vogue. We continue to exist on stolen land from murdered indigenous
        peoples, and we continue the theft along with the murder. Canada went on to suppress other minorities (any list
        would oversimplify) much of which continues today. It makes us uniquely able to study the topic, to review our
        history, to understand today, and to prepare for tomorrow. As Heschel said “We are not all guilty, but we are
        all responsible.”
    </p>
    <p>
        In this contemporary review, we hope to better comprehend the past and the present from our current standpoint.
        The topics are broad and can only be understood with serious analysis of its different embodiments. It’s
        possible that, given the constantly changing abuses, a study of genocides and political violence will never be
        complete. As such, we hope to make a small contribution to a global exchange.
    </p>
{% endblock blurb %}

website/templates/website/list_articles.html
{% extends "layout.html" %}
{% load static %}
{% load extras %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/list_articles.css" %}?ver={{ css_version }}">
{% endblock head %}

{% block main %}
    <main>
        {% if category %}
            <div class="subcategories d-flex flex-wrap justify-content-center">
                {% for subcategory in category.subcategories.all %}
                    <a id="subcategory" class="btn btn-outline-secondary mx-2" href="{% url "website:list_sub_articles" subcategory.pk %}">
                        {{ subcategory.name|category_parse }}
                    </a>
                {% endfor %}
            </div>
        {% endif %}


        <div id="content" class="d-xl-flex justify-content-center">

            <div id="articles">

                <p id="context"><u>
                    {% if fields %}
                        Results containing: <b>"{{ fields }}"</b>:
                    {% elif subcategory %}
                        Articles from <b>{{ subcategory }}</b>
                    {% elif category %}
                        Articles from <b>{{ category }}</b>
                    {% endif %}
                </u></p>

                {% for article in articles %}
                    {% if article != feature_article %}
                        <a href="{% url "website:article_detail" article.pk %}">
                            <div class="article d-flex flex-column-reverse flex-md-row justify-content-between">
                                <div class="text_info">
                                    <p class="article_title">{{ article.title }}</p>
                                    {% if article.preview %}<p class="article_preview"><em>{{ article.preview }}</em></p>{% endif %}
                                    <p class="article_author">{{ article.author.name }}</p>
                                    <p class="article_date">{{ article.date }}</p>
                                </div>
                                {% if article.image %}<div class="image" style="background-image:url({{ article.image.url }})"></div>{% endif %}
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>

            {% if feature_article %}
                <a id="feature_link" href="{% url "website:article_detail" feature_article.pk%}">
                    <div id="feature">
                        <p id="featured_in"><small>Featured in {{ category }}:</small></p>
                        {% if feature_article.image %}
                            <div class="image mx-auto" style="background-image:url({{ feature_article.image.url }})"></div>
                        {% endif %}
                        <p class="article_title">{{ feature_article.title }}</p>
                        {% if feature_article.preview %}
                            <p class="article_preview"><em>{{ feature_article.preview }}</em></p>
                        {% endif %}
                        <p class="article_author">{{ feature_article.author.name }}</p>
                        <p class="article_date">{{ feature_article.date }}</p>
                    </div>
                </a>
            {% endif %}

        </div>


        <div class="pagination justify-content-center">
            <span class="step-links">
                {% if articles.has_previous %}
                    <span class="page_buttons">
                        <a href="?page=1">&laquo; </a>
                        <a href="?page={{ articles.previous_page_number }}">&lsaquo;</a>
                    </span>
                {% endif %}

                <span class="current">
                    Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
                </span>

                {% if articles.has_next %}
                    <span class="page_buttons">
                        <a href="?page={{ articles.next_page_number }}">&rsaquo;</a>
                        <a href="?page={{ articles.paginator.num_pages }}"> &raquo;</a>
                    </span>
                {% endif %}
            </span>
        </div>
    </main>
{% endblock main %}

{% block scripts %}
    <script src="{% static "js/list_articles.js" %}?ver={{ css_version }}"></script>
{% endblock scripts %}

website/templates/website/menu_bar.html
<nav id="menu_bar" class="navbar navbar-expand-lg navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url "website:home" %}">Home</a>
            </li>
            {% for category in categories %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "website:list_articles"  category.pk %}">{{ category }}</a>
                </li>
            {% endfor %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "website:introductions" %}">About Us</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

website/templates/website/our_team.html
{% extends 'website/about.html' %}

{% block title %}Our Team{% endblock title %}

{% block blurb %}
    <h1>Our Team</h1>
    <p>
        <span class="name">Gideon Salutin</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:gideon.salutin@gmail.com">gideon.salutin@gmail.com</a><br>
        <em>Editor-in-Chief</em>
    </p>
    <p>
        <span class="name">Brandon Heiblum</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:genocidesjournal@gmail.com">genocidesjournal@gmail.com</a><br>
        <em>Public Relations Coordinator</em>
    </p>

    <h3 class="designation"><u>Current Events</u></h3>
    <p>
        <span class="name">Gavin Jolly</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:gavin.jolly@mail.mcgill.ca">gavin.jolly@mail.mcgill.ca</a><br>
        <em>Primary Editor of Current Events</em>
    </p>
    <p>
        <span class="name">Alexandra Beaudry</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:alexa.beaudry@gmail.com">alexa.beaudry@gmail.com</a><br>
        <em>Current Events Staff Writer</em>
    </p>
    <p>
        <span class="name">Shira Garbis</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:shira.garbis@mail.mcgill.ca">shira.garbis@mail.mcgill.ca</a><br>
        <em>Current Events Staff Writer</em>
    </p>
    <p>
        <span class="name">Louise Vuilimin</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:louise.vuillemin@mail.mcgill.ca">louise.vuillemin@mail.mcgill.ca</a><br>
        <em>Current Events Staff Writer</em>
    </p>

    <h3 class="designation"><u>History</u></h3>
    <p>
        <span class="name">Salma Addas</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:salma.addas@mail.mcgill.com">salma.addas@mail.mcgill.com</a><br>
        <em>Primary Editor of History</em>
    </p>
    <p>
        <span class="name">Brandon Heiblum</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:brandon.heiblum@mail.mcgill.ca">brandon.heiblum@mail.mcgill.ca</a><br>
        <em>Secondary Editor of History</em>
    </p>
    <p>
        <span class="name">Maggie Munro</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:maggie.munro@mail.mcgill.ca">maggie.munro@mail.mcgill.ca</a><br>
        <em>Secondary Editor of History</em>
    </p>
    <p>
        <span class="name">Andrea Corkel</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:andrea.corkal@mail.mcgill.ca">andrea.corkal@mail.mcgill.ca</a><br>
        <em>History Staff Writer</em>
    </p>
    <p>
        <span class="name">Reilly Dunne</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:reilly.dunne9@gmail.com">reilly.dunne9@gmail.com</a><br>
        <em>History Staff Writer</em>
    </p>
    <p>
        <span class="name">Sanskruti Patel</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:sanskruti.patel@mail.mcgill.ca">sanskruti.patel@mail.mcgill.ca</a><br>
        <em>History Staff Writer</em>
    </p>
    <p>
        <span class="name">Romane Savard-Guzman</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:romane.savard-guzman@mail.mcgill.ca">romane.savard-guzman@mail.mcgill.ca</a><br>
        <em>History Staff Writer</em>
    </p>

    <h3 class="designation"><u>Law & Theory</u></h3>
    <p>
        <span class="name">Amelia Williams</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:amelia.williams@mail.mcgill.ca">amelia.williams@mail.mcgill.ca</a><br>
        <em>Primary Editor of Law and Theory</em>
    </p>
    <p>
        <span class="name">Kemal Kongar</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:kemal.kongar@mail.mcgill.ca">kemal.kongar@mail.mcgill.ca</a><br>
        <em>Secondary Editor of Law and Theory</em>
    </p>
    <p>
        <span class="name">Ismail Ameen</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:ismail.ameen@mail.mcgill.ca">ismail.ameen@mail.mcgill.ca</a><br>
        <em>Law and Theory Staff Writer</em>
    </p>
    <p>
        <span class="name">Owain Guinn</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:owain.guinn@mail.mcgill.ca">owain.guinn@mail.mcgill.ca</a><br>
        <em>Law and Theory Staff Writer</em>
    </p>
    <p>
        <span class="name">Cameron Hirschkorn</span> &nbsp&nbsp-&nbsp&nbsp <a href="mailto:cameron.hirschkorn@mail.mcgill.ca">cameron.hirschkorn@mail.mcgill.ca</a><br>
        <em>Law and Theory Staff Writer</em>
    </p>
    <br>
    <br>
    <p>Website made by Stephen Edwards &nbsp&nbsp-&nbsp&nbsp <a href="mailto:ssedward@edu.uwaterloo.ca">ssedward@edu.uwaterloo.ca</a></p>


{% endblock blurb %}

website/templates/website/to_publish.html
{% extends 'website/about.html' %}

{% block title %}To Publish{% endblock title %}

{% block blurb %}
            <h1>To Publish</h1>
            <p><em><u>What we publish</u></em></p>
            <p>
                Genocide is a difficult term, subject to debate.  We publish art and articles related to genocide and political
                violence.  We cover topics in history and current events, domestically and internationally.  We also cover
                issues in international law, and theoretical subjects like “how does political violence begin?”  Any topics
                related to mass violence, hate crimes, suppression, can be submitted along with any themes you feel should
                relate.
            </p>
            <p><em><u>Who can apply?</u></em></p>
            <p>
                While our editing team is centered at McGill, you don’t have to be a McGill student to submit.  You do not need
                references or documented experience.  If you have a topic, and can articulate it well, we welcome your input.
            </p>
            <p><em><u>To Submit</u></em></p>
            <p>
                Write an email to <a href="mailto:genocidesjournal@gmail.com">genocidesjournal@gmail.com</a> and you will be
                forwarded to the appropriate editing section. You can write us:
            <ol type="a">
                <li>a pitch, where we will discuss and develop the idea</li>
                <li>a work in progress, where we will assist in its completion</li>
                <li>a complete work for us to review</li>
            </ol>
            Send us a note today!
            </p>
{% endblock blurb %}